import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import Logo from "./life-eco-modern.png"
export const metadata: Metadata = {
  title: "Lekos ERP",
  description: "Generated by create next app",
  icons: {
    icon: "./life-eco-modern.png"
  }
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
